name: CI-CD Common Pipeline

on:
  workflow_call:
    inputs:
      component:
        required: true
        type: string
      appType:
        required: true
        type: string
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: clean package
        if: ${{  inputs.appType == 'java' }}
        run: mvn clean package
      - name: upload artifact
        if: ${{  inputs.appType == 'java' }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{  inputs.component  }}-jar
          path: target/${{  inputs.component  }}-1.0.jar
          retention-days: 1
  test:
    runs-on: self-hosted
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo npm test
  docker:
    runs-on: self-hosted
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: download artifact
        if: ${{  inputs.appType == 'java' }}
        uses: actions/download-artifact@v4
        with:
          name: ${{  inputs.component  }}-jar
          path: ./

      - name: Build Image
        run: docker build --load -t ${{  inputs.component  }} .

      - name: Tag Image
#        run: docker tag ${{  inputs.component  }} roboshop5427.azurecr.io/${{  inputs.component  }}:${{ github.sha }}
        run: docker tag ${{  inputs.component  }} roboshop5427.azurecr.io/${{  inputs.component  }}:latest

      - name: Push Image
        run: docker push roboshop5427.azurecr.io/${{  inputs.component  }}:latest

  dev-deploy:
    runs-on: self-hosted
    environment: dev
    needs: docker
    steps:
      - uses: actions/checkout@v4
        with:
          repository: Sandeepkumar0088/azure-helm-charts
      - name: Azure Login
        uses: azure/login@v3
        with:
          auth-type: IDENTITY
          subscription-id: "bb2e4b65-7863-4a64-99b2-cd7d29b73bd7"
          tenant-id: "525ac05a-796a-4239-a302-33808d9d2c38"

      - name: get kubectl config
        run: az aks get-credentials --resource-group cluster --name dev --overwrite-existing

      - name: helm deploy app
        run: helm upgrade -i ${{  inputs.component  }}:latest . -f templates/${{  inputs.component  }}.yml  --install --take-ownership

  qa-deploy:
    runs-on: self-hosted
    needs: dev-deploy
    environment: qa
    steps:
      - uses: actions/checkout@v4
        with:
          repository: Sandeepkumar0088/roboshop-helm-charts-v1

      - name: get kubectl config
        run: echo aws eks update-kubeconfig --name qa

      - name: helm deploy app
        run: echo helm upgrade -i ${{  inputs.component  }} .

  uat-deploy:
    runs-on: self-hosted
    needs: qa-deploy
    environment: uat
    steps:
      - uses: actions/checkout@v4
        with:
          repository: Sandeepkumar0088/roboshop-helm-charts-v1
      - name: get kubectl config
        run: echo aws eks update-kubeconfig --name uat
      - name: helm deploy app
        run: echo helm upgrade -i ${{  inputs.component  }} . -f dev-values/${{  inputs.component  }}.yml

  prod-deploy:
    runs-on: self-hosted
    needs: uat-deploy
    environment: prod
    steps:
      - uses: actions/checkout@v4
        with:
          repository: Sandeepkumar0088/roboshop-helm-charts-v1
      - name: echo get kubectl config
        run: echo aws eks update-kubeconfig --name prod
      - name: helm deploy app
        run: echo helm upgrade -i ${{  inputs.component  }} . -f dev-values/${{  inputs.component  }}.yml